version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      # Используем переменную KAFKA_CFG_ZOOKEEPER_CONNECT, чтобы Kafka знала, где найти Zookeeper:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - app-network

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: bookstorage
      POSTGRES_USER: bookuser
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    networks:
      - app-network

  book-storage-service:
    build: ./book-storage-service
    container_name: book-storage-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bookstorage
      SPRING_DATASOURCE_USERNAME: bookuser
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - kafka
      - zookeeper
    networks:
      - app-network

  book-tracker-service:
    build: ./book-tracker-service
    container_name: book-tracker-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/booktracker
      SPRING_DATASOURCE_USERNAME: trackeruser
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - kafka
      - zookeeper
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
