version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  book-storage-service:
    build: ./book-storage-service
    container_name: book-storage-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bookstorage
      SPRING_DATASOURCE_USERNAME: bookuser
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - zookeeper
      - postgres

  book-tracker-service:
    build: ./book-tracker-service
    container_name: book-tracker-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/booktracker
      SPRING_DATASOURCE_USERNAME: trackeruser
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - zookeeper
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: bookstorage
      POSTGRES_USER: bookuser
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
